[package]
name = "rex-machina"
version = "0.1.0"
edition = "2021"

[lib]
name = "rex"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.68"
bigerror = "0.1.0"
dashmap = "5.4.0"
futures = "0.3.28"
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["sync", "time", "rt"] }
tokio-stream = "0.1.14"
tracing = "0.1.37"
tracing-test = "0.2.4"
uuid = "1.3.2"
# cargo add async-trait dashmap bigerror futures thiserror tokio-stream tracing tracing-test uuid
# cargo add tokio --features sync,time
